include(unpack)

set(EIGEN_HOME "${LIBS_DIRECTORY}/eigen")
set(EIGEN_PACKAGE_NAME eigen-3.2.10.tar.bz2)
set(EIGEN_PACKAGE "${EIGEN_HOME}/${EIGEN_PACKAGE_NAME}")
set(EIGEN_UNPACK_DIR ${CMAKE_BINARY_DIR})
set(EIGEN_SOURCE_HOME ${EIGEN_UNPACK_DIR}/eigen-eigen-b9cd8366d4e8)

set(EIGEN_INCLUDE_DIR ${EIGEN_SOURCE_HOME})

unpack(EIGEN ${EIGEN_PACKAGE} ${EIGEN_UNPACK_DIR})
