include(unpack)

set(NUKLEAR_PACKAGE_NAME nuklear.zip)
set(NUKLEAR_HOME "${LIBS_DIRECTORY}/nuklear")
set(NUKLEAR_PACKAGE "${NUKLEAR_HOME}/${NUKLEAR_PACKAGE_NAME}")
set(NUKLEAR_UNPACK_DIR ${CMAKE_BINARY_DIR})

unpack(NUKLEAR ${NUKLEAR_PACKAGE} ${NUKLEAR_UNPACK_DIR})

set(NUKLEAR_INCLUDE_DIR ${NUKLEAR_UNPACK_DIR}/nuklear)
